name: wiser
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  liquid_swipe: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6
  rive: ^0.10.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  google_sign_in: ^5.4.2
  font_awesome_flutter: ^10.3.0
  currency_text_input_formatter: ^2.1.8
  flutter_iconpicker: ^3.2.2
  enefty_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0

# App icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/wiser_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/rive_animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
