name: wiser
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  liquid_swipe: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0

# App icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/wiser_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/wiser_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
          style: italic
