// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzWUzs_-OTA1VfjKkgu9NKkXkEQuYGbA',
    appId: '1:789994417782:web:6e72ff1b5b7e624f713957',
    messagingSenderId: '789994417782',
    projectId: 'wiser-d49c2',
    authDomain: 'wiser-d49c2.firebaseapp.com',
    storageBucket: 'wiser-d49c2.appspot.com',
    measurementId: 'G-XWFTCGPQG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VuRhNiSe-WTeCyVPF7GbNrQTj66nDwM',
    appId: '1:789994417782:android:813b4c9ef80f3a68713957',
    messagingSenderId: '789994417782',
    projectId: 'wiser-d49c2',
    storageBucket: 'wiser-d49c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60enCloD-oM8rh9G3Y2YWoR1T6r-5t_k',
    appId: '1:789994417782:ios:0fe222c151312db6713957',
    messagingSenderId: '789994417782',
    projectId: 'wiser-d49c2',
    storageBucket: 'wiser-d49c2.appspot.com',
    androidClientId: '789994417782-tcgbih1ct63l2eu3lh3sgu4i3ssnnm6j.apps.googleusercontent.com',
    iosClientId: '789994417782-ssegok7rm36hlo8r5j2bprk694giub4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60enCloD-oM8rh9G3Y2YWoR1T6r-5t_k',
    appId: '1:789994417782:ios:0fe222c151312db6713957',
    messagingSenderId: '789994417782',
    projectId: 'wiser-d49c2',
    storageBucket: 'wiser-d49c2.appspot.com',
    androidClientId: '789994417782-tcgbih1ct63l2eu3lh3sgu4i3ssnnm6j.apps.googleusercontent.com',
    iosClientId: '789994417782-ssegok7rm36hlo8r5j2bprk694giub4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiser',
  );
}
